<?xml version="1.0"?>
<robot name="bender" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="pi" value="3.141592653589794" />
    <xacro:property name="base_len" value="0.89" />
    <xacro:property name="base_wid" value="0.80" />
    <xacro:property name="base_height" value="0.20" />
    <xacro:property name="caster_length" value="0.10" />
    <xacro:property name="caster_radius" value="0.15" />
    <xacro:property name="wheel_length" value="0.10" />
    <xacro:property name="wheel_radius" value="0.15" />

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
          <mass value="${mass}" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>


    <material name="white">
       <color rgba="1 1 1 1"/>
    </material>

    <link name="base_link">
        <visual>
          <geometry>
            <box size="${base_len} ${base_wid} ${base_height}"/>
          </geometry>
          <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <box size="${base_len} ${base_wid} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>


    <joint name="base_to_front_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="front_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${base_wid/2} 0 ${-1*base_height}" rpy="${pi/2} 0 0"/>
    </joint>
    <link name="front_wheel">
        <visual>
            <geometry>
                <cylinder length = "${caster_length}" radius="${caster_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <cylinder length = "${caster_length}" radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="2"/>
    </link>


    <joint name="base_to_back_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="back_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${-1*base_wid/2} 0 ${-1*base_height}" rpy="${pi/2} 0 0"/>
    </joint>
    <link name="back_wheel">
        <visual>
            <geometry>
                 <cylinder length = "${caster_length}" radius="${caster_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <cylinder length = "${caster_length}" radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="2"/>
    </link>


    <joint name="base_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0 ${-1*base_wid/2} ${-1*base_height}" rpy="${pi/2} 0 0"/>
    </joint>
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length = "${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <cylinder length = "${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="5"/>
    </link>


    <joint name="base_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0 ${base_wid/2} ${-1*base_height}" rpy="${pi/2} 0 0"/>
    </joint>
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length = "${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <cylinder length = "${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="5"/>
    </link>

 <!-- Gazebo plugin for ROS Control -->

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo>

</robot>
